### ISSUE TITLE
Feature: API

### ISSUE THREAD

**Issue by KatzeMau** [SCDerox/FragCaesar#1]
Could you add an API?
And / or a translation function for sentences

**Comment by SCDerox** [comment]
Hey, thanks for your issue. "FragCaesar" is a package that uses the website [frag-caesar.de](https://www.frag-caesar.de/). Unfortunately this website does not provide any system to translate sentences. I also don't know any good Latin-translation sites (I guess there is not a big enough market for such sites), so you could try [Google Translate](https://translate.google.com) but the translation there is garbage most of the time. The [site](frag-caesar.de) has no official API, this package does only scrap the content of the site (and does it poorly, a lot of data is missing or wrong). I personally do not have any plans to add more features to this package (like an API or something) or to fix any bugs in this package. You can of course use the very limited functions exported from `index.js` in your own project if you want to.
